In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import numpy as np
print(np.__version__)

1.24.3


In [12]:
a = np.array([2,24,45,56,67,778,8,85])
print(a)
b = np.arange(start=23, stop=45, step=2)
b


[  2  24  45  56  67 778   8  85]


array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43])

In [13]:
c = np.array([False for x in range(10)])
c

array([False, False, False, False, False, False, False, False, False,
       False])

In [16]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
a = np.full((3,3), True, dtype=bool)
print(a)
b = np.full(4,4, dtype = int)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[4 4 4 4]


In [ ]:
c = np.ones((3,3), dtype=bool)
c

d = np.ones((16),dtype=bool).reshape(8,2)
d

In [25]:
# Extract all even and add numbers

a = np.arange(16)
print(a)

print(a[a%2 == 1])

print(a[a%2 == 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  3  5  7  9 11 13 15]
[ 0  2  4  6  8 10 12 14]


In [27]:
arr = np.arange(16)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1])

In [32]:
# Question: Replace all odd numbers in arr with -1 without changing arr

b = np.arange(16)

# if we done a = b then if we make any changes in "a" then changes will reflect on a

a = b.copy()
a[a%3 == 0] = -11
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[-11   1   2 -11   4   5 -11   7   8 -11  10  11 -11  13  14 -11]


In [36]:
# Exercise 7. How to reshape an array?

c = np.arange(30)
print(c.reshape(3,10))
print(c.reshape(5,6))


print(c.reshape(10, -1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [40]:
# Question: Stack arrays a and b vertically

# Learning Both matrix should be of same size
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])